version: '3.7'
services:
  prod:
    container_name: react-app-prod
    image: react-app-prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 80:3000

  dev:
    container_name: react-app-dev
    image: react-app-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 8080:3000
